//设置当前选中元素
const RENDER_TREE_SET_TARGET_ELEMENT_CHECKED_KEY = 'RENDER_TREE_SET_TARGET_ELEMENT_CHECKED_KEY';
//页面(根元素)新增元素
const RENDER_TREE_CREATE_PAGE_ROOT_ELEMENT = 'RENDER_TREE_CREATE_PAGE_ROOT_ELEMENT';
//元素位置对换
const RENDER_TREE_ELEMENT_POSITION_SWAP = 'RENDER_TREE_ELEMENT_POSITION_SWAP';
//在元素后追加新元素
const RENDER_TREE_ADD_TO_ELEMENT = 'RENDER_TREE_ADD_TO_ELEMENT'
//元素插入操作（同级元素操作）
const RENDER_TREE_INSERT_TO_ELEMENT = 'RENDER_TREE_INSERT_TO_ELEMENT'
//元素插入操作(父级元素操作)
const RENDER_TREE_INSERT_TO_PARENT_ELEMENT = 'RENDER_TREE_INSERT_TO_PARENT_ELEMENT'
//根据ID获取数据信息
const RENDER_TREE_GET_ELEMENT_DATA_BY_ID = 'RENDER_TREE_GET_ELEMENT_DATA_BY_ID'
//根据ID修改对应参数
const RENDER_TREE_UPDATE_ELEMENT_DATA_BY_ID = 'RENDER_TREE_UPDATE_ELEMENT_DATA_BY_ID'
//根据ID删除对应元素
const RENDER_TREE_DELETE_ELEMENT_BY_ID = 'RENDER_TREE_DELETE_ELEMENT_BY_ID'
//数据复制
const RENDER_TREE_COPY_ELEMENT_BY_ID = 'RENDER_TREE_COPY_ELEMENT_BY_ID'
//修改元素label
const RENDER_TREE_UPDATE_ELEMENT_LABEL_BY_ID = 'RENDER_TREE_UPDATE_ELEMENT_LABEL_BY_ID'
//根据id元素插入操作
const RENDER_TREE_INSERT_TO_ELEMENT_BY_ID = 'RENDER_TREE_INSERT_TO_ELEMENT_BY_ID'
//替换schema
const RENDER_TREE_SCHEMA_REPLACE = 'RENDER_TREE_SCHEMA_REPLACE'


export default {
  RENDER_TREE_SET_TARGET_ELEMENT_CHECKED_KEY,
  RENDER_TREE_CREATE_PAGE_ROOT_ELEMENT,
  RENDER_TREE_ELEMENT_POSITION_SWAP,
  RENDER_TREE_ADD_TO_ELEMENT,
  RENDER_TREE_INSERT_TO_ELEMENT,
  RENDER_TREE_INSERT_TO_PARENT_ELEMENT,
  RENDER_TREE_GET_ELEMENT_DATA_BY_ID,
  RENDER_TREE_UPDATE_ELEMENT_DATA_BY_ID,
  RENDER_TREE_DELETE_ELEMENT_BY_ID,
  RENDER_TREE_COPY_ELEMENT_BY_ID,
  RENDER_TREE_UPDATE_ELEMENT_LABEL_BY_ID,
  RENDER_TREE_INSERT_TO_ELEMENT_BY_ID,
  RENDER_TREE_SCHEMA_REPLACE
}
