//设置当前选中元素
const RENDER_TREE_SET_TARGET_ELEMENT_CHECKED_KEY = 'RENDER_TREE_SET_TARGET_ELEMENT_CHECKED_KEY';
//页面(根元素)新增元素
const RENDER_TREE_CREATE_PAGE_ROOT_ELEMENT = 'RENDER_TREE_CREATE_PAGE_ROOT_ELEMENT';
//元素位置对换
const RENDER_TREE_ELEMENT_POSITION_SWAP = 'RENDER_TREE_ELEMENT_POSITION_SWAP';
//在元素后追加新元素
const RENDER_TREE_ADD_TO_ELEMENT = 'RENDER_TREE_ADD_TO_ELEMENT'

export default {
  RENDER_TREE_SET_TARGET_ELEMENT_CHECKED_KEY,
  RENDER_TREE_CREATE_PAGE_ROOT_ELEMENT,
  RENDER_TREE_ELEMENT_POSITION_SWAP,
  RENDER_TREE_ADD_TO_ELEMENT

}
