export default [
  {
    label:'容器',
    value:'container',
    items:[
      {
        label:'基础容器',
        value:'container1',
        searchEKEY:'JCRQ1',
        icon:'icon-yemiankuangjia_o'
      },
      {
        label:'基础容器1',
        value:'container2',
        searchEKEY:'JCRQ2',
        icon:'icon-yemiankuangjia_o'
      },
      {
        label:'FLEX',
        value:'container3',
        searchEKEY:'FLEX',
        icon:'icon-yemiankuangjia_o'
      },
      {
        label:'行',
        value:'container4',
        searchEKEY:'H',
        icon:'icon-yemiankuangjia_o'
      },
      {
        label:'列',
        value:'container5',
        searchEKEY:'L',
        icon:'icon-yemiankuangjia_o'
      },
    ]
  },
  {
    label:'组件',
    value:'container6',
    items:[
      {
        label:'表格',
        value:'container7',
        searchEKEY:'BG',
        icon:'icon-yemiankuangjia_o'
      },
      {
        label:'图表',
        value:'container8',
        searchEKEY:'TB',
        icon:'icon-yemiankuangjia_o'
      },
      {
        label:'轮播图',
        value:'container9',
        searchEKEY:'LBT',
        icon:'icon-yemiankuangjia_o'
      },
      {
        label:'走马灯',
        value:'container10',
        searchEKEY:'ZMT',
        icon:'icon-yemiankuangjia_o'
      },
      {
        label:'手风琴',
        value:'container11',
        searchEKEY:'SFQ',
        icon:'icon-yemiankuangjia_o'
      },
    ]
  }
]
