//更新插件状态---切换
const UPDATE_PLUGIN_DRAWER_TARGET = 'UPDATE_PLUGIN_DRAWER_TARGET'
const UPDATE_PLUGIN_DRAWER_VISIBLE = 'UPDATE_PLUGIN_DRAWER_VISIBLE'
const UPDATE_PLUGIN_DRAWER_FIXED = 'UPDATE_PLUGIN_DRAWER_FIXED'
const UPDATE_PLUGIN_SETTING_FOLD = 'UPDATE_PLUGIN_SETTING_FOLD'
const UPDATE_PLUGIN_SETTING_CHILD_ITEM_COLLAPSE = 'UPDATE_PLUGIN_SETTING_CHILD_ITEM_COLLAPSE'
const UPDATE_PLUGIN_SETTING_CHILD_ITEM_IS_CAN_MOVE_STATUS = 'UPDATE_PLUGIN_SETTING_CHILD_ITEM_IS_CAN_MOVE_STATUS'
export default {
  UPDATE_PLUGIN_DRAWER_TARGET,
  UPDATE_PLUGIN_DRAWER_VISIBLE,
  UPDATE_PLUGIN_DRAWER_FIXED,
  UPDATE_PLUGIN_SETTING_FOLD,
  UPDATE_PLUGIN_SETTING_CHILD_ITEM_COLLAPSE,
  UPDATE_PLUGIN_SETTING_CHILD_ITEM_IS_CAN_MOVE_STATUS
}
