//更新插件状态---切换
const UPDATE_PLUGIN_DRAWER_TARGET = 'UPDATE_PLUGIN_DRAWER_TARGET'
const UPDATE_PLUGIN_DRAWER_VISIBLE = 'UPDATE_PLUGIN_DRAWER_VISIBLE'
const UPDATE_PLUGIN_DRAWER_FIXED = 'UPDATE_PLUGIN_DRAWER_FIXED'
const UPDATE_PLUGIN_SETTING_FOLD = 'UPDATE_PLUGIN_SETTING_FOLD'
export default {
  UPDATE_PLUGIN_DRAWER_TARGET,
  UPDATE_PLUGIN_DRAWER_VISIBLE,
  UPDATE_PLUGIN_DRAWER_FIXED,
  UPDATE_PLUGIN_SETTING_FOLD
}
